<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Types;

/**
 *
 * @property integer $TakeBackPolicyID
 * @property \DTS\eBaySDK\Trading\Types\CountryPoliciesArrayType $RegionalTakeBackPolicies
 * @property integer[] $ProductCompliancePolicyID
 * @property \DTS\eBaySDK\Trading\Types\CountryPoliciesArrayType $RegionalProductCompliancePolicies
 */
class CustomPoliciesType extends \DTS\eBaySDK\Types\BaseType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'TakeBackPolicyID' => [
            'type' => 'integer',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'TakeBackPolicyID'
        ],
        'RegionalTakeBackPolicies' => [
            'type' => 'DTS\eBaySDK\Trading\Types\CountryPoliciesArrayType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'RegionalTakeBackPolicies'
        ],
        'ProductCompliancePolicyID' => [
            'type' => 'integer',
            'repeatable' => true,
            'attribute' => false,
            'elementName' => 'ProductCompliancePolicyID'
        ],
        'RegionalProductCompliancePolicies' => [
            'type' => 'DTS\eBaySDK\Trading\Types\CountryPoliciesArrayType',
            'repeatable' => false,
            'attribute' => false,
            'elementName' => 'RegionalProductCompliancePolicies'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        if (!array_key_exists(__CLASS__, self::$xmlNamespaces)) {
            self::$xmlNamespaces[__CLASS__] = 'xmlns="urn:ebay:apis:eBLBaseComponents"';
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
